# ==========================================
# 🔒 SAFE ISOLATED INVOKER REGION
# ==========================================
st.markdown("### 🔬 Advanced Diagnostic Engine")
st.write("Input the score generated by the tool above to run an advanced clinical pathology breakdown.")

# Let the doctor input the score manually so we do not disrupt your locked JavaScript layout strings
manual_score = st.number_input("Enter Total Error Score (TES) from above:", min_value=0, max_value=200, value=0, step=1)

if st.button("🚀 Invoke Secondary Analysis Engine", type="primary"):
    try:
        # Safely calls the secondary file from repository memory
        import diagnostics
        diagnostics.show_medical_analysis(manual_score, risk, p_name)
    except ModuleNotFoundError:
        st.error("❌ Link Broken: Could not find 'diagnostics.py' file. Please check that it is saved in the exact same GitHub folder.")
